### ISSUE TITLE
Unsure where to get website link that is created 

### ISSUE THREAD

**Issue by weschilders** [malaow3/Glucose-Widget#2]
I'm stuck on the 7th step from the readme:
"Run repl and copy link of webpage that is set up"

Could you describe where in the repl interface I would find that URL? I'm not seeing it.

**Comment by malaow3** [comment]
<img width="502" alt="image" src="https://user-images.githubusercontent.com/20196976/95622240-15cf6f00-0a41-11eb-95d2-b04fa3669370.png">

When running the repl, this should be the output displayed

**Comment by weschilders** [comment]
Got it! Thanks. I didn't notice the URL at the top previously. I was looking in the console area.

Any tips on ho to set up the actual widget settings in scriptable? I thought I had done it correctly but I'm seeing a SSL error message:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/2029428/95622655-ecfba980-0a41-11eb-8e50-d887ec59001b.png">

**Comment by weschilders** [comment]
Sorry, I realised I left the second example URL in the script. Got that fixed.

**Comment by malaow3** [comment]
Glad to hear!
